"""Criando tabela cadastro_produto

Revision ID: 4bebc80c99c8
Revises: 
Create Date: 2026-03-16 19:52:25.249012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bebc80c99c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigoprod', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastro_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastro_produto_codigoprod'), ['codigoprod'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastro_produto_codigoprod'))

    op.drop_table('cadastro_produto')
    # ### end Alembic commands ###
