"""empty message

Revision ID: 57b67d242e3e
Revises: 
Create Date: 2024-10-21 13:31:47.342888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b67d242e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigoprod', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigoprod')
    )
    op.drop_table('cadastro_produtos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro_produtos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigoprod', sa.INTEGER(), nullable=False),
    sa.Column('produto', sa.VARCHAR(length=100), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigoprod')
    )
    op.drop_table('cadastro_produto')
    # ### end Alembic commands ###
