"""empty message

Revision ID: d422e6872dbf
Revises: 
Create Date: 2024-11-19 18:45:37.026578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd422e6872dbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_produto', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.SMALLINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('codigoprod',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('quantidade',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_produto', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
        batch_op.alter_column('codigoprod',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
